---

- name: Install git client
  yum: name=git state=present

- name: Install rpm-build
  yum: name=rpm-build state=present

- name: Export git repo from code.grnet.gr
  tags: checkout
  git: repo=https://code.grnet.gr/git/ar-ng
       dest=/root/ar-ng force=yes update=yes

- name: Install golang package (building dep)
  yum: name=golang state=present

- name: Install bzr package (building dep)
  yum: name=bzr state=present

- name: Install maven2 package (building dep)
  yum: name=maven2 state=present

- name: Install java-1.7.0-openjdk-devel package (building dep)
  yum: name=java-1.7.0-openjdk-devel state=present

- name: Build targets
  tags: build
  shell: make rpms
         chdir=/root/ar-ng/builder
         creates=/root/rpmbuild
