---

- hosts: ar-builders
  user: root
  gather_facts: no
  roles:
    - start_synnefo_vm

- hosts: ar-builders
  user: root
  roles:
    - common
    - repos
    - builder
    - ca_bundle
    - kojiclient

- hosts: ar-builders
  user: root
  gather_facts: no
  roles:
    - stop_synnefo_vm