- name: Ensure the VM is stopped
  delegate_to: 127.0.0.1
  synnefo_compute:
     name=ar-centos-builder
     state=stopped
     wait=yes
     token='{{ synnefo_token }}'
     auth_url='https://accounts.okeanos.grnet.gr/identity/v2.0'
